/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CreatorRouteImport } from './routes/creator'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SuccessRouteImport } from './routes/success'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as UUsernameRouteImport } from './routes/u.$username'
import { Route as ApiPublicOutboundRouteImport } from './routes/api/public/outbound'
import { Route as ApiPublicReleasePayoutsRouteImport } from './routes/api/public/release-payouts'
import { Route as ApiPublicShareAvatarRouteImport } from './routes/api/public/share-avatar'
import { Route as ApiPublicStripeWebhookRouteImport } from './routes/api/public/stripe-webhook'
import { Route as ApiPublicTmpDiagRouteImport } from './routes/api/public/tmp-diag'
import { Route as ApiPublicXCallbackRouteImport } from './routes/api/public/x-callback'
import { Route as ApiPublicXStartRouteImport } from './routes/api/public/x-start'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CreatorRoute = CreatorRouteImport.update({
  id: '/creator',
  path: '/creator',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SuccessRoute = SuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const UUsernameRoute = UUsernameRouteImport.update({
  id: '/u/$username',
  path: '/u/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicOutboundRoute = ApiPublicOutboundRouteImport.update({
  id: '/api/public/outbound',
  path: '/api/public/outbound',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicReleasePayoutsRoute = ApiPublicReleasePayoutsRouteImport.update({
  id: '/api/public/release-payouts',
  path: '/api/public/release-payouts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicShareAvatarRoute = ApiPublicShareAvatarRouteImport.update({
  id: '/api/public/share-avatar',
  path: '/api/public/share-avatar',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStripeWebhookRoute = ApiPublicStripeWebhookRouteImport.update({
  id: '/api/public/stripe-webhook',
  path: '/api/public/stripe-webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTmpDiagRoute = ApiPublicTmpDiagRouteImport.update({
  id: '/api/public/tmp-diag',
  path: '/api/public/tmp-diag',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXCallbackRoute = ApiPublicXCallbackRouteImport.update({
  id: '/api/public/x-callback',
  path: '/api/public/x-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicXStartRoute = ApiPublicXStartRouteImport.update({
  id: '/api/public/x-start',
  path: '/api/public/x-start',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/faq': typeof FaqRoute
  '/owners': typeof OwnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/outbound': typeof ApiPublicOutboundRoute
  '/api/public/release-payouts': typeof ApiPublicReleasePayoutsRoute
  '/api/public/share-avatar': typeof ApiPublicShareAvatarRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tmp-diag': typeof ApiPublicTmpDiagRoute
  '/api/public/x-callback': typeof ApiPublicXCallbackRoute
  '/api/public/x-start': typeof ApiPublicXStartRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/faq': typeof FaqRoute
  '/owners': typeof OwnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/outbound': typeof ApiPublicOutboundRoute
  '/api/public/release-payouts': typeof ApiPublicReleasePayoutsRoute
  '/api/public/share-avatar': typeof ApiPublicShareAvatarRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tmp-diag': typeof ApiPublicTmpDiagRoute
  '/api/public/x-callback': typeof ApiPublicXCallbackRoute
  '/api/public/x-start': typeof ApiPublicXStartRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/contact': typeof ContactRoute
  '/creator': typeof CreatorRoute
  '/faq': typeof FaqRoute
  '/owners': typeof OwnersRoute
  '/privacy': typeof PrivacyRoute
  '/reset-password': typeof ResetPasswordRoute
  '/success': typeof SuccessRoute
  '/terms': typeof TermsRoute
  '/u/$username': typeof UUsernameRoute
  '/api/public/outbound': typeof ApiPublicOutboundRoute
  '/api/public/release-payouts': typeof ApiPublicReleasePayoutsRoute
  '/api/public/share-avatar': typeof ApiPublicShareAvatarRoute
  '/api/public/stripe-webhook': typeof ApiPublicStripeWebhookRoute
  '/api/public/tmp-diag': typeof ApiPublicTmpDiagRoute
  '/api/public/x-callback': typeof ApiPublicXCallbackRoute
  '/api/public/x-start': typeof ApiPublicXStartRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/creator'
    | '/faq'
    | '/owners'
    | '/privacy'
    | '/reset-password'
    | '/success'
    | '/terms'
    | '/u/$username'
    | '/api/public/outbound'
    | '/api/public/release-payouts'
    | '/api/public/share-avatar'
    | '/api/public/stripe-webhook'
    | '/api/public/tmp-diag'
    | '/api/public/x-callback'
    | '/api/public/x-start'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/creator'
    | '/faq'
    | '/owners'
    | '/privacy'
    | '/reset-password'
    | '/success'
    | '/terms'
    | '/u/$username'
    | '/api/public/outbound'
    | '/api/public/release-payouts'
    | '/api/public/share-avatar'
    | '/api/public/stripe-webhook'
    | '/api/public/tmp-diag'
    | '/api/public/x-callback'
    | '/api/public/x-start'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/about'
    | '/admin'
    | '/auth'
    | '/contact'
    | '/creator'
    | '/faq'
    | '/owners'
    | '/privacy'
    | '/reset-password'
    | '/success'
    | '/terms'
    | '/u/$username'
    | '/api/public/outbound'
    | '/api/public/release-payouts'
    | '/api/public/share-avatar'
    | '/api/public/stripe-webhook'
    | '/api/public/tmp-diag'
    | '/api/public/x-callback'
    | '/api/public/x-start'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  ContactRoute: typeof ContactRoute
  CreatorRoute: typeof CreatorRoute
  FaqRoute: typeof FaqRoute
  OwnersRoute: typeof OwnersRoute
  PrivacyRoute: typeof PrivacyRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SuccessRoute: typeof SuccessRoute
  TermsRoute: typeof TermsRoute
  UUsernameRoute: typeof UUsernameRoute
  ApiPublicOutboundRoute: typeof ApiPublicOutboundRoute
  ApiPublicReleasePayoutsRoute: typeof ApiPublicReleasePayoutsRoute
  ApiPublicShareAvatarRoute: typeof ApiPublicShareAvatarRoute
  ApiPublicStripeWebhookRoute: typeof ApiPublicStripeWebhookRoute
  ApiPublicTmpDiagRoute: typeof ApiPublicTmpDiagRoute
  ApiPublicXCallbackRoute: typeof ApiPublicXCallbackRoute
  ApiPublicXStartRoute: typeof ApiPublicXStartRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creator': {
      id: '/creator'
      path: '/creator'
      fullPath: '/creator'
      preLoaderRoute: typeof CreatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/success': {
      id: '/success'
      path: '/success'
      fullPath: '/success'
      preLoaderRoute: typeof SuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/u/$username': {
      id: '/u/$username'
      path: '/u/$username'
      fullPath: '/u/$username'
      preLoaderRoute: typeof UUsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/outbound': {
      id: '/api/public/outbound'
      path: '/api/public/outbound'
      fullPath: '/api/public/outbound'
      preLoaderRoute: typeof ApiPublicOutboundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/release-payouts': {
      id: '/api/public/release-payouts'
      path: '/api/public/release-payouts'
      fullPath: '/api/public/release-payouts'
      preLoaderRoute: typeof ApiPublicReleasePayoutsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/share-avatar': {
      id: '/api/public/share-avatar'
      path: '/api/public/share-avatar'
      fullPath: '/api/public/share-avatar'
      preLoaderRoute: typeof ApiPublicShareAvatarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stripe-webhook': {
      id: '/api/public/stripe-webhook'
      path: '/api/public/stripe-webhook'
      fullPath: '/api/public/stripe-webhook'
      preLoaderRoute: typeof ApiPublicStripeWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/tmp-diag': {
      id: '/api/public/tmp-diag'
      path: '/api/public/tmp-diag'
      fullPath: '/api/public/tmp-diag'
      preLoaderRoute: typeof ApiPublicTmpDiagRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x-callback': {
      id: '/api/public/x-callback'
      path: '/api/public/x-callback'
      fullPath: '/api/public/x-callback'
      preLoaderRoute: typeof ApiPublicXCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/x-start': {
      id: '/api/public/x-start'
      path: '/api/public/x-start'
      fullPath: '/api/public/x-start'
      preLoaderRoute: typeof ApiPublicXStartRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  ContactRoute: ContactRoute,
  CreatorRoute: CreatorRoute,
  FaqRoute: FaqRoute,
  OwnersRoute: OwnersRoute,
  PrivacyRoute: PrivacyRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SuccessRoute: SuccessRoute,
  TermsRoute: TermsRoute,
  UUsernameRoute: UUsernameRoute,
  ApiPublicOutboundRoute: ApiPublicOutboundRoute,
  ApiPublicReleasePayoutsRoute: ApiPublicReleasePayoutsRoute,
  ApiPublicShareAvatarRoute: ApiPublicShareAvatarRoute,
  ApiPublicStripeWebhookRoute: ApiPublicStripeWebhookRoute,
  ApiPublicTmpDiagRoute: ApiPublicTmpDiagRoute,
  ApiPublicXCallbackRoute: ApiPublicXCallbackRoute,
  ApiPublicXStartRoute: ApiPublicXStartRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
